<?php

namespace Blog\ModelBundle\Repository;
use Blog\ModelBundle\Entity\Author;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find the first author
     *
     * @return Author
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findFirst(){
        $qb = $this->getQueryBuilder()
                ->orderBy('a.id', 'asc')
                ->setMaxResults(1);

        return $qb->getQuery()->getSingleResult();
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getQueryBuilder(){
        $em = $this->getEntityManager();

        $qb = $em->getRepository("ModelBundle:Author")
                ->createQueryBuilder('a');

        return $qb;
    }
}
